stages:
- name: Get Latest Commit ID
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: commit_id = $(git rev-parse --verify HEAD)
    env:
      COMMIT_ID: ${commit_id}
- name: Build and Push Images
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mbhaskar2005/firstdockerrepo:${COMMIT_ID}
      pushRemote: true
      registry: https://hub.docker.com/repository/docker/mbhaskar2005/firstdockerrepo
timeout: 60
branch: {}
notification: {}
