stages:
- name: Get Latest Commit ID
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: LCOMMIT_ID=$(git rev-parse --verify HEAD)
    env:
      COMMIT_ID: ${LCOMMIT_ID}
- name: Build and Push Images
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mbhaskar2005/firstdockerrepo:${COMMIT_ID}
      pushRemote: true
      registry: https://hub.docker.com/repository/docker/mbhaskar2005/firstdockerrepo
timeout: 60
branch:
  include:
  - Push
notification: {}
