stages:
- name: Get Latest Commit ID
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        LCOMMIT_ID=$(git rev-parse --verify HEAD)

        echo ${COMMIT_ID}
    env:
      COMMIT_ID: ${LCOMMIT_ID}
- name: Build and Push Images
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        echo ${COMMIT_ID}
        $(docker build . -t mbhaskar2005/firstdockerrepo:${COMMIT_ID})

        $(docker login -u mbhaskar2005 -p ${docker-pwd})

        $(docker push mbhaskar2005/firstdockerrepo:${COMMIT_ID})
    envFrom:
    - sourceName: s-hzvht
      sourceKey: passwd
      targetKey: docker-pwd
timeout: 60
branch:
  include:
  - master
notification: {}
