apiVersion: v1
kind: Service
metadata:
  name: communications
  labels:
    app: communications
spec:
  ports:
  - name: http
    targetPort: 7001
    port: 80
  selector:
    app: communications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: communications
  labels:
    app: communications
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communications
      version: v1
  template:
    metadata:
      labels:
        app: communications
        version: v1
    spec:
      imagePullSecrets:
      - name: nexus
      containers:
      -env:
       - name: NSL_VCS_HOST
         value: 18.191.115.25 
      - name: communications
        image: nexus.nslhub.com/comm-rancher-prod:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: communications
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /send
    route:
    - destination:
        host: communications
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: communications
spec:
  host: communications
