apiVersion: v1
kind: Service
metadata:
  name: nginxpage
  labels:
    app: nginxpage
    service: nginxpage
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: nginxpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpage-v1
  labels:
    app: nginxpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxpage
      version: v1
  template:
    metadata:
      labels:
        app: nginxpage
        version: v1
    spec:
      containers:
      - name: nginxpage
        image: mbhaskar2005/firstdockerrepo:tagVersion
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginxpage
spec:
  hosts:
  - nginxpage
  http:
  - match:
    - uri:
        exact: /nginx
  http:
  -match:
      ur
  - route:
    - destination:
        host: nginxpage
        subset: v1
        port:
          number: 8080
