apiVersion: v1
kind: Pod
metadata:
  name: newpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newpod
  template:
    metadata:
      labels:
        app: newpod
    spec:
      imagePullSecrets:
      - name: docksec
      containers:
      - name: newpod
        imagePullPolicy: IfNotPresent
        image: mbhaskar2005/firstdockerrepo:tagVersion
        ports:
            - containerPort: 8080
