apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: test
    image: mbhaskar2005/firstdockerrepo:tagVersion
    imagePullPolicy: Never
  imagePullSecrets:
  - name: docksecr
      
