apiVersion: v1
kind: Pod
metadata:
  name: testa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testa
  template:
    metadata:
      labels:
        app: testa
    spec:
      imagePullSecrets:
      - name: docksec
      containers:
      - name: testa
        imagePullPolicy: IfNotPresent
        image: mbhaskar2005/firstdockerrepo:tagVersion
        ports:
        - containerPort: 8080
