apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  imagePullSecrets:
  - name: docksecr
  containers:
  - name: test
    image: mbhaskar2005/firstdockerrepo:tagVersion
    ports:
        - containerPort: 8080
      
