apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  imagePullSecrets:
  - name: docksecr
  containers:
  - name: test
    image: nexus.nslhub.com/utility-rancher-prod:1
    ports:
        - containerPort: 8080
      
