apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
    - name: test
      image: mbhaskar2005/firstdockerrepo:tagVersion
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: testquay
      
