apiVersion: v1
kind: Pod
metadata:
  name: newpod
spec:
  selector:
    matchLabels:
      app: newpod
      version: v1
  imagePullSecrets:
  - name: docksec
  containers:
  - name: newpod
    imagePullPolicy: IfNotPresent
    image: mbhaskar2005/firstdockerrepo:tagVersion
    ports:
        - containerPort: 8080
      
