apiVersion: v1
kind: Pod
metadata:
  name: appnode
  labels:
    app: appnode
spec:
  containers:
    - name: appnode
      image: mbhaskar2005/firstdockerrepo:tagVersion
  imagePullSecrets:
    - name: docker
      ports:
        - containerPort: 8080
